
language: c++
matrix:
  include:
  - os: linux
    script:
    - chmod +x cmakeify
    - ./cmakeify -wf . --group-id com.github.jomof --artifact-id freetype --target-version ${TRAVIS_TAG:-0.0.0}
    - ./cdep
    - ./cmakeify -wf .cdep/examples/cmake
